// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenUIClient is the client API for TokenUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenUIClient interface {
	// ListEngineSpecs returns a list of Token Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (TokenUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type tokenUIClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenUIClient(cc grpc.ClientConnInterface) TokenUIClient {
	return &tokenUIClient{cc}
}

func (c *tokenUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (TokenUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &TokenUI_ServiceDesc.Streams[0], "/v1.TokenUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &tokenUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TokenUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type tokenUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *tokenUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *tokenUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.TokenUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenUIServer is the server API for TokenUI service.
// All implementations must embed UnimplementedTokenUIServer
// for forward compatibility
type TokenUIServer interface {
	// ListEngineSpecs returns a list of Token Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, TokenUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedTokenUIServer()
}

// UnimplementedTokenUIServer must be embedded to have forward compatible implementations.
type UnimplementedTokenUIServer struct {
}

func (UnimplementedTokenUIServer) ListEngineSpecs(*ListEngineSpecsRequest, TokenUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedTokenUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedTokenUIServer) mustEmbedUnimplementedTokenUIServer() {}

// UnsafeTokenUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenUIServer will
// result in compilation errors.
type UnsafeTokenUIServer interface {
	mustEmbedUnimplementedTokenUIServer()
}

func RegisterTokenUIServer(s grpc.ServiceRegistrar, srv TokenUIServer) {
	s.RegisterService(&TokenUI_ServiceDesc, srv)
}

func _TokenUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TokenUIServer).ListEngineSpecs(m, &tokenUIListEngineSpecsServer{stream})
}

type TokenUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type tokenUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *tokenUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _TokenUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.TokenUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TokenUI_ServiceDesc is the grpc.ServiceDesc for TokenUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TokenUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.TokenUI",
	HandlerType: (*TokenUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _TokenUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _TokenUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "token-ui.proto",
}
